workflows:
  unity-ios-workflow:
    name: Unity iOS Workflow
    environment:
      groups:
        - unity_credentials
        - app_store_credentials
      vars:
        UNITY_BIN: $UNITY_HOME/Contents/MacOS/Unity
        BUILD_SCRIPT: BuildScript.BuildIOS
    scripts:
      - name: Activate Unity License
        script: |
          $UNITY_BIN -batchmode -quit -logFile \
            -serial ${UNITY_SERIAL} -username ${UNITY_USERNAME} -password ${UNITY_PASSWORD}
      - name: Build Unity Project
        script: |
          $UNITY_BIN -quit -batchmode -logFile -projectPath . \
            -executeMethod $BUILD_SCRIPT -nographics
      - name: Export Unity
        script: |
          cd ios
          /usr/bin/xcodebuild -workspace Unity-iPhone.xcworkspace -scheme Unity-iPhone -sdk iphoneos -configuration Release clean archive -archivePath build-output/app.xcarchive
          /usr/bin/xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output -exportOptionsPlist ExportOptions.plist
    artifacts:
      - ios/*.ipa
